package(default_visibility = ["//visibility:public"])
cc_library(
  name = "zip_wrapper",
  hdrs = ["zip_wrapper.h"],
  srcs = ["zip_wrapper.cc"],
  deps = [
    "//common:common",
    "@zlib//:zlib"
  ],
)